const CITY_PROVINCE_MAP: Record<string, string> = {
  "madrid": "prov.madrid",
  "barcelona": "prov.barcelona",
  "valencia": "prov.valencia",
  "sevilla": "prov.sevilla",
  "zaragoza": "prov.zaragoza",
  "malaga": "prov.malaga",
  "murcia": "prov.murcia",
  "palma": "prov.baleares",
  "palma de mallorca": "prov.baleares",
  "las palmas": "prov.las_palmas",
  "las palmas de gran canaria": "prov.las_palmas",
  "bilbao": "prov.bizkaia",
  "alicante": "prov.alicante",
  "cordoba": "prov.cordoba",
  "valladolid": "prov.valladolid",
  "vigo": "prov.pontevedra",
  "gijon": "prov.asturias",
  "hospitalet": "prov.barcelona",
  "l'hospitalet de llobregat": "prov.barcelona",
  "vitoria": "prov.alava",
  "vitoria-gasteiz": "prov.alava",
  "granada": "prov.granada",
  "elche": "prov.alicante",
  "oviedo": "prov.asturias",
  "santa cruz de tenerife": "prov.tenerife",
  "badalona": "prov.barcelona",
  "cartagena": "prov.murcia",
  "terrassa": "prov.barcelona",
  "jerez": "prov.cadiz",
  "jerez de la frontera": "prov.cadiz",
  "sabadell": "prov.barcelona",
  "mostoles": "prov.madrid",
  "alcala de henares": "prov.madrid",
  "pamplona": "prov.navarra",
  "fuenlabrada": "prov.madrid",
  "almeria": "prov.almeria",
  "leganes": "prov.madrid",
  "san sebastian": "prov.gipuzkoa",
  "donostia": "prov.gipuzkoa",
  "donostia-san sebastian": "prov.gipuzkoa",
  "santander": "prov.cantabria",
  "burgos": "prov.burgos",
  "castellon": "prov.castellon",
  "castellon de la plana": "prov.castellon",
  "albacete": "prov.albacete",
  "getafe": "prov.madrid",
  "alcorcon": "prov.madrid",
  "salamanca": "prov.salamanca",
  "logrono": "prov.rioja",
  "huelva": "prov.huelva",
  "badajoz": "prov.badajoz",
  "tarragona": "prov.tarragona",
  "lleida": "prov.lleida",
  "leon": "prov.leon",
  "cadiz": "prov.cadiz",
  "jaen": "prov.jaen",
  "ourense": "prov.ourense",
  "lugo": "prov.lugo",
  "girona": "prov.girona",
  "caceres": "prov.caceres",
  "huesca": "prov.huesca",
  "toledo": "prov.toledo",
  "pontevedra": "prov.pontevedra",
  "ciudad real": "prov.ciudad_real",
  "a coruna": "prov.coruna",
  "la coruna": "prov.coruna",
  "coruña": "prov.coruna",
  "guadalajara": "prov.guadalajara",
  "cuenca": "prov.cuenca",
  "avila": "prov.avila",
  "segovia": "prov.segovia",
  "palencia": "prov.palencia",
  "zamora": "prov.zamora",
  "soria": "prov.soria",
  "teruel": "prov.teruel",
  "ceuta": "prov.ceuta",
  "melilla": "prov.melilla",
  "marbella": "prov.malaga",
  "torremolinos": "prov.malaga",
  "benidorm": "prov.alicante",
  "ibiza": "prov.baleares",
  "san fernando": "prov.cadiz",
  "ronda": "prov.malaga",
  "sitges": "prov.barcelona",
  "figueres": "prov.girona",
  "santiago de compostela": "prov.coruna",
};

function normalize(str: string): string {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
}

// Build normalized lookup map at module load
const NORMALIZED_MAP: Record<string, string> = {};
for (const [key, value] of Object.entries(CITY_PROVINCE_MAP)) {
  NORMALIZED_MAP[normalize(key)] = value;
}

export function inferProvince(city: string): string | null {
  return NORMALIZED_MAP[normalize(city)] ?? null;
}
